name: Deno

on:
  workflow_dispatch: # Permite ejecutar la acción manualmente

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [v1.1.2, v1.0.0]  # Puedes agregar más versiones según lo necesites

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: ${{ matrix.deno-version }}  # Utiliza la versión de la matriz

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      # - name: Verify formatting
      #   run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A

